export const UNIT_FETCH_ALL  = "UNIT_FETCH_ALL";
export const ADDED_UNIT = "ADDED_UNIT";
export const HANDLE_ERROR_UNIT = "HANDLE_ERROR_UNIT";
export const DELETED_UNIT = "DELETED_UNIT";
export const START_UNIT_FETCHING = "START_UNIT_FETCHING"