name: Build CI

on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  react_ci:
    name: React Build CI
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: yarn install
      run: yarn install
    - name: yarn run build
      run: yarn run only-build
  dotnet_ci:
    name: Dotnet Core Build CI
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
