name: Node CI

on: 
  push :
    branches : 
      - develop
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest
  steps:
      uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
